version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongodata:/data/db

  back-java:
      build: ./backend-java        
      container_name: backend-java 
      restart: always
      environment:
        SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongo:27017/
      ports:
        - "8080:8080"
      links:
        - mongo
          
volumes:
  mongodata:
